### ISSUE TITLE
Not really an issue, but strange: Unexpected TII-Data

### ISSUE THREAD

**Issue by Walter0799** [softsyst/qirx_issues#139] opened 2024-01-25 17:09 UTC
I'm in the test phase with Qirx, and I really like its presentation of TII-Data, but in one case I get fully unexpected results.

This does not seem to be a Qirx issue, because Qt-Dab does not show the same but similar unexpected results on same receiver and same antennas.

It relates to one ensemble only: 11D - Radio fuer NRW.

My receiver's site is about 16km north of the 10kW Dortmund transmitter and I expected to see "Dortmund/Florianturm" as (at least main) transmitter site.

But I see rapidly changing (up to 6 times per second)

- Meschede 1/Fernmeldeturm
- Eggegebirge/Lichtenau
- Teutoburger Wald/Bielstein
- Bielefeld/Hünenburg

and other transmitters I never would have expected to see in the list, because their transmitting power is too low and/or mountains and hills shield them in my direction. Plus an empty entry Main 99 Sub 2 ????

"Dortmund/Florianturm" appears very rarely. 

I then thought of Dortmund overloading the RSPdx with active antenna, played around with gain, LNA state and TII Threshold - no change. Eventually I connected a passive antenna: Same result. But when I switch to 5C, Dortmund appears immediately with a strenght of 0.999 to 1 - that's what I expected on 11D.

As I said: I do not think this is a Qirx issue, since the TII data in all other ensembles make sense and are as expected. Some surprises, but sensible.

What is striking: the spectrum of 11D looks completely different from the other ensembles. Does the WDR has a different coding of TII?

I carefully read Clem's abstract on decoding TII data and seems to me the WDR does something unexpected in 11D.

What do you think causes this? Do you want more information on this? Input? Files? Logging? If yes, what and how?

**Comment by softsyst** [comment] 2024-01-25 21:06
Hi Walter,

If you have the TII threshold properly adjusted (for such a case you need to switch from auto to manual), I cannot give you an explanation. I could have a look if you could upload somewhere (e.g. Google dropbox) a raw file of at least one minute (about 250MB, in any case such a length that the problems show up). and send me the link (or publish here, as you like) As I am in Frankfurt/M, I cannot receive the WDR, but had no report about problems.
As a remark (which you perhaps already know), you should adjust the TII threshold well above the noise, by observing it in the TII spectrum (gray rectangle at the bottom). And if you increase the "TII averaging", you should - in that spectrum - see the noise going down.
Of course, this does not exclude an "issue" somewhere. I really would be interested to have a look.

Regards,
Clem

**Comment by Walter0799** [comment] 2024-01-26 08:31
Thanks Clem,

I will do more playing around with TII Threshold and check for some webspace to upload a minute of raw data.

But since my test license lasts another 8 days, let me check something else first: Since the spectrum of 11D looks so differently from all others I've ever seen, and I must admit, I never put my attention on this, 

5C
![Screenshot 5C](https://github.com/softsyst/qirx_issues/assets/157721290/e14f8e79-d45b-46e5-9aa9-8370a668e6b2)

11D
![Screenshot 11D](https://github.com/softsyst/qirx_issues/assets/157721290/3fd0c6d2-537b-4731-9559-6e9df79f723e)

I've had the idea last night that something from the neighborhood (or myself :-( ) interferes with 222.064 MHz. More and more disturbing electronical devices in the past, anyway. So I will take my notebook over the weekend, go to some recreational space nearby - where I can be sure that no devices are producing anything bad - and check the spectrum there with Qt-Dab or SDRUno (no licencse for Qirx on my notebook). And with SDRTouch on my mobile. If the spectrum looks different then, the issue comes from the neighborhood.

I'll let you know asap.

Cheers
Walter

**Comment by softsyst** [comment] 2024-01-26 11:28
Walter,

both spectra look quite good and totally normal. The 11D pattern stems from the fact that you receive more than one transmitter, causing the characteristic ripple, from the (non-destructive) interference of more than one transmitter. With your spectrum, you should see two (or more weak) peaks in the 11D CIR spectrum, each corresponding to a transmitter (or a multipath reflection). If their distance difference is indicated as less than 75km, then you receive them within the guard interval, and both make a positive contribution to the signal, This distance difference must be read with caution though, as the operators often infer some artificial delay due to their network planning.

As another remark, please be aware that you could request a second license key for your notebook. This holds also for the Demo licenses.

And last not least in your first notice you mentioned a TII Main Id of 99, which indicates a "Tii Collision". Please see the tutorial on my website about this issue and the problems it causes with TII decoding.

Regards,
Clem

**Comment by superblyb** [comment] 2024-01-27 18:41
11D has been subject in an earlier issue. 
There are many transmitters of 11D. In my region I have a lot of TII collisions for 11D.
@Walter : try marking "Show collisions for sub ID [1, 2 or 3]" and there will be differences on the main screen. Note that "99" marks a pseudo value where there are probably TII-collisions. Note that on the map, everything seems to be shown correctly.

**Comment by superblyb** [comment] 2024-01-27 19:00
With 11D, sometimes it is hard to say if all the values are real. Also, the values keep changing fast.

![11D](https://github.com/softsyst/qirx_issues/assets/129985820/a70fb61b-addd-452b-8520-12a6fa9e06c0)
![11D-2](https://github.com/softsyst/qirx_issues/assets/129985820/2e4d188c-eade-4014-af65-fba3735543f5)
![11D-3](https://github.com/softsyst/qirx_issues/assets/129985820/16c89160-0c79-4dd4-be30-b40072b9e3d2)

It has been a lot worse in earlier versions.
Note that if you uncheck to mark the TII-collisions, the map will show good results.

**Comment by superblyb** [comment] 2024-01-27 19:24
Turning off the AGC turns out to give better results (the treshold is being changed if you do so).

**Comment by Walter0799** [comment] 2024-01-28 07:56
Seems I forget to post my answer before I shutdown the PC on Friday.

I now understand and tested everything Clem and superblyb said: Match!

Remains the question to Clem: still interested in a one minute 11D raw recoding?

Otherwise you can close this.

Cheers
Walter

**Comment by softsyst** [comment] 2024-01-28 10:42
Walter,

if it would be possible: yes. I am always interested in looking at difficult receiving situations, if I have the chance to.

Thanks,
Clem

**Comment by Walter0799** [comment] 2024-01-29 09:00
Here we go, Clem. A friend uploaded the file to a server were you can anonymously download it till tomorrow night, 185MB 7z-file:

https://jollyjellyfish-sto.energycdn.com/dl/tFw3ZBbcUQtL2z_Fu2oCQw/1707073937/745939183/65b6a6fb8b75a2.79302683/2024_01_28_19_50_30_2048000_11D_fHz222064000.7z

Cheers and have fun analysing it ... Can **I** replay that file in Qirx somehow? Did not find anything in the GUI, think SDR_tcp can read it with a secret parameter?

**Comment by softsyst** [comment] 2024-01-29 12:25
Thanks, Walter. I downloaded your file, and it really is a very nice example of a TII collision. Whoever decided to give the transmitters these numbers, certainly had something different in mind than analyzing TII Ids. Hard to understand.

Anyway, first your question: In QIRX, the simplest way to replay a raw file is to drag it somewhere over the "Frontend" section of its GUI, and drop it. That's all. In addition, in contrast to your assumption it is also mentioned on the website (for the V2, but V3 and V4 is just the same): Menu "Operation, Playground", then click into the upper right rectangle, clicking the glowing circle gets you the following  at the bottom of the page :
![image](https://github.com/softsyst/qirx_issues/assets/51386375/29bf02f6-ea36-472e-b908-e0de5d9d0cec)
with a description of the blue and green triangles at the right corner, serving to start either a live stream or a file stream.

Now let us have a look at the TII spectrum of your raw file. The picture shows a zoomed highly resolved extract of the middle compartment, i.e. one of the four parts limited by yellow dashed lines and which all carry the same info. See either the ETSI Standard, or my "TII collision" tutorial which explains it in more detail.

![image](https://github.com/softsyst/qirx_issues/assets/51386375/ee0f354e-51be-4630-9141-278ec933df1e)

This picture can show us some interesting info:
I limit my discussion to the info within the green rectangle, above a (thought) threshold indicated by the red line.
- If you have a keen look at the lines you always see two of them. This indicates that these are real TII carriers which always come in pairs separated by 1kHz, and not some noise. Please note that the pairs are only resolved in the "High Resolution" display, not in the normal display where the two are drawn as a single one.
- If during replay of your file you hover over each of the carrier pairs in the green box, you get the information that all of them have the "SubId" of 1. You could do this of course also with the "normal-resolution" display. Thus, you have in the drawn "compartment" at least six lines (=carrier pairs) with a SubId of 1. What does that mean?
- Remember the "TII collision" tutorial: The "compartment" is divided into eight equally spaced parts, of which exactly four should contain a carrier for a TII identification with the same SubId, which has the value of 1 in your example file. For different SubIds it is the same game. Each combination of four is called a "pattern". Each pattern is mapped 1:1 to a Main Id.
- Now look at the picture: We have not four carrier pairs, but six. This means that each four combinations of these six carriers "COULD" stem from a real transmitter. If you remember school math, if you make all combinations of four out of a set of six, you get 15 possibilities ("6 over 4"). 
- Now please decide: You have 15 possible tranmitter TII Ids from your six carrier pairs, each with a different Main Id, all with a Sub Id of 1. Which of them are really received?
- Bad news: QIRX can't decide, so we are in a dilemma, caused by the clever guy who assigned these numbers to the transmitter TIIs.

What could you do?
1. If you follow @superblyb's advice and check "Show Collisions for SubId", with SubId of 1, then all possible 15 combinations are listed. Not all of them have names, so you could decide to restrict your search to the one with names, and make a plausible selection with respect to your geo location.
2. If you have a directional rotatable antenna, you could let it show into different directions and observe how the height of the TII carriers shrinks or grows. Remember: Of your six carrier pairs only some of the combinations of four are from a real transmitter. "Looking" away from that transmitter, his carriers should shrink, according to the forward/backward relation of your antenna. This could give you a strong hint which "carrier pair combinations of four" could stem from real transmitters.

This is TII Collisions in a nutshell...

Regards,
Clem

**Comment by Walter0799** [comment] 2024-01-30 09:39
Thanks for that detailed explanations, Clem.

TII on WDR 11D looks more like the RDS Alternative Frequency feature ... wondering what happens when the WDR starts on 9A this year as planned. I'll check immediately! When the WDR was testing DRM on mediumwave I had a good contact to the Head of transmission technique, but unfortunately he's no longer in place ...

I think there are two things I can do:

1. as you say solving the dilemma in seeing which transmitter is more likely, but that's really not easy in an area I do not know
2. hope that everywhere I go and make a DAB bandscan, the people responsible for TII assign better IDs

The rest I will deal with as soon as I find the time.

Cheers
Walter

**Comment by softsyst** [comment] 2024-01-30 11:02
Thanks for the response, Walter.
I close this one.

**Closed as completed by softsyst** 2024-01-30 11:02 UTC
