### ISSUE TITLE
Audio prob on mux 7A only?

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#17] opened 2021-08-23 12:34 UTC
When firing up QIRX on 7A I have audio. Switching to another strong mux: perfect. Switching back to 7A: audio gone and also no audio on other muxes. Sometimes it takes a few times switching back to 7A before the audio stops. It only seems to occur on 7A.
Shutting down the rx won't fix it. I do get audio back after a full Qirx restart.
When this occurs and I open the qirx_audio.exe box in the taksbar the bow closes itself after a few seconds.

**Comment by softsyst** [comment] 2021-08-24 22:27
Can't reproduce it here. Maybe a raw file will help to find the (presumable) bug.

**Comment by softsyst** [comment] 2021-08-28 16:38
Thanks to [Herman's](https://www.wijnants.info/fmdx/) raw data, the error in qirx_audio could be reproduced, and fixed in sequence. The new version 1.3 is on GitHub and the binary will be distributed with the next QIRX version 3.1.7. The issue is closed.

**Closed as completed by softsyst** 2021-08-28 16:38 UTC
Labels: bug
