### ISSUE TITLE
Lost SPI logo for Oldie Antenne on 5D

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#130] opened 2024-01-05 22:40 UTC
Hi Clem,

While playing around with the new version 4.2.1 I noticed this:
The images for Oldie Antenne aren't displayed:
![5D_SPI_Lost_OldieAnt_V421_](https://github.com/softsyst/qirx_issues/assets/49753409/80287763-65a3-4622-abcd-ef05257277f2)

However, the images can be found in the temp folder:
[V421_5C_Temp_969b8b58-b394-400f-a2f6-46ac6d5b559d.zip](https://github.com/softsyst/qirx_issues/files/13847244/V421_5C_Temp_969b8b58-b394-400f-a2f6-46ac6d5b559d.zip)

Without rebuilding the SPI folder I wouldn't have noticed it...

Regards,
cgfan

**Comment by softsyst** [comment] 2024-01-05 23:19
Just had a quick look in their metadata. In the .EIB file, they write their own name not correct. They write Oldi Antenne (sic!). Maybe this is the problem, would be similar to the DLF errors. Will check tomorrow.
The name in the .EIB file does not coincide with the one coming across the DAB transmission.
Thanks for the remark.

**Comment by softsyst** [comment] 2024-01-06 00:15
Just had another look. The problem is that Oldie Antenne does not send its SId which is found in the 9B. It is 121D, and the one sent via SPI is 1A9A. And  as a consequence1A9A and not 121D is in the list together with the logo pictures.
The Ensemble Id EId is the correct one, 11F7.
This seems to be a link to another SId of the service, there is an entry in the 
[rundfunkforum](https://www.rundfunkforum.de/viewtopic.php?f=11&t=55499&start=10800)
Despite this possible link (which QIRX does not handle)  the SPI should show its main SId.

![image](https://github.com/softsyst/qirx_issues/assets/51386375/ac156e34-b097-499d-a711-a31c69ffc5a1)

**Comment by softsyst** [comment] 2024-01-06 10:43
Not a problem of qirx: I close it.

**Closed as completed by softsyst** 2024-01-06 10:43 UTC
