### ISSUE TITLE
DAB scan saving

### ISSUE THREAD

**Issue by PiNoise** [softsyst/qirx_issues#79] opened 2023-03-04 07:32 UTC
HI Clem

Little question.
In Option / DAB Scan where is the data saved?
After scanning and clicking on "Save Scan Settings" I expected the data to be saved and stored internally.

![screen](https://user-images.githubusercontent.com/26836104/222882393-bf4952b9-ebbd-4202-b63e-518343d240a8.jpg)

Instead always after I close and restart Qirx I have to do it all over again as I do not find the previously saved information.
Surely I am not performing some step correctly. Where is it that I am doing wrong?

Many thanks,
Paolo R.

**Comment by softsyst** [comment] 2023-03-04 10:39
Hi Paolo,

it was not a feature, but a bug! Please download and install again the 4.0.7. I (hopefully) silently corrected this which had slipped in inadvertently as a side effect from another feature. In case you are not sure whether the version you downloaded is already the one in the web, please compare the SHA-1 values.

**Edit**: Sorry, Paolo, I just forgot to answer your question: The scan data is saved in the config file, here:
    <Demodulator Id="0" Name="DAB">

      <DAB>
        <SNR DeltaSound_dB="5" />
        <Ensemble channel="12C" service="Rheinwelle 92,5" udpIPAddress="255.255.255.255" udpPort="8765" muted="no" />
        <Ensembles value="5C,7B,9B,10A,11D,12C" />
        <GUI SelecteTabIndex="1" />
        <TII Threshold="0.728" Average="1" />
        <Scanner AutoMode="no" Forever="yes" DelayTime="0" DelayTimeBefore="2" MinLevel="7" Ensembles="5A,5B,5C,5D,6A,6B,6C,6D,7A,7B,7C,7D,8A,8B,8C,8D,9A,9B,9C,9D,10A,10B,10C,10D,11A,11B,11C,11D,12A,12B,12C,12D" />
        <AudioRecorder Type="WAV" />
        <AutoCalibrate value="yes" />
      </DAB>

The entry in the "Ensembles" tag indicate the saved results of the scan. The ones in the  "Scanner ... Ensembles=..."  tag indicate the Blocks participating in the scan.

73,
Clem

**Comment by PiNoise** [comment] 2023-03-05 18:03
ciao Clem

I just tried the new 4.0.7 (silent) that you kindly modified.
I uninstalled the previous one for the new one, but unfortunately it still seems not to work properly for that bug.
In scan it finds me the following mux's, writes about the save, but as soon as I close and restart with the program they are all gone....

**Comment by PiNoise** [comment] 2023-03-05 18:05
At startup QIRX sets up on channel 5C (??, it is not present here...), and displays for a new scan showing all in the drop-down list all channels 5/13 and no longer just my previously saved six muxes, as you can see here...
![image1](https://user-images.githubusercontent.com/26836104/222977752-fa4a71dc-5692-4d44-bd47-8be4dda11522.png)
![image2](https://user-images.githubusercontent.com/26836104/222977759-d225c8cb-015e-413d-842b-6cb7bce4d45a.png)

**Comment by softsyst** [comment] 2023-03-05 19:17
Hi Paolo,

No idea about your problem. Here it works as it should:
1. All muxes are enabled, like so:

![BeforeScan](https://user-images.githubusercontent.com/51386375/222980441-41051b21-ad9a-46e2-a44c-5082952f03f1.jpg)

2. Result of a scan, stopped during 2nd run:

![DuringScan](https://user-images.githubusercontent.com/51386375/222980468-ca1d69c4-2c8e-4cb5-9270-46384a72c879.jpg)

3. After storing, stopping the app and restarting it:

![ResultAfterScan](https://user-images.githubusercontent.com/51386375/222980504-0321c423-82d5-42d6-8d9e-0f632da11a20.jpg)

The mux 5C is the German Federal mux. It is the default value for a fresh config file, as the first selected value. It is of course later overwritten with the one you listened to. QIRX cannot know which mux is available at your location on first start after installation, or after a new config has been generated.

Did you check the SHA-1 value?

73,
Clem

**Comment by PiNoise** [comment] 2023-03-06 07:51
Ciao Clem!

I really don't know what to think at this point... other than some limitation or restriction due to my firewalls/antivirus/etc etc.
If I can I will do more testing on a secondary pc as soon as I can.
Thanks for your immediate and accurate feedback.

Yes the SHA-1 value is correct:
00ae05fe76b951f43c65e1128f16f20c9984caea *my QIRX407_Setup.msi
00ae05fe76b951f43c65e1128f16f20c9984caea original

73, Paolo

**Comment by andimik** [comment] 2023-03-06 08:21
Just a stupid idea (therefore sorry for that):

Are you using the same Windows account before and after saving?

**Comment by PiNoise** [comment] 2023-03-06 08:37
Every question is pertinent when dealing with Windows, hehe... 
Yes always same Windows account, my laptop is single user.

**Comment by softsyst** [comment] 2023-03-06 12:07
Hi Paolo,
you mentioned that also your scan settings are not persisted, so that you each time need to adjust them again. This could mean that the software either stores in a different location than the one it reads from, or that the config file could be write protected.
This sounds as stupid as andimik's assumption, but the devil is a squirrel (as we say here).

My tests of yesterday have been done with the version directly from the download, fresh install, with the SHA-1 which you also confirmed.

73,
Clem

**Comment by PiNoise** [comment] 2023-03-06 13:15
Hi Clem,
There is something going wrong here, sometimes yes sometimes no and therefore difficult to find out. 
Lately also I have been asked to enter the license which apparently had been lost or not saved correctly!!!

My directory where the configuration is saved is
C:\USERS\xxx\AppData\Local\Qirx4

but I see now that it also exists on today's date:
C:\USERS\xxx\AppData\Local\QirxConsole

Two oddities in my system just uncovered thanks to the TotalCommander browser:
(a) The "AppData" subdirectory alone has the hidden attribute, while all subsequent subdirectories have no attribute.
b) I don't have QirxConsole installed but its subdirecotry is present and up to date as of now.

Windows is really a mine of criticalities and absurdities

73, Paolo

**Comment by PiNoise** [comment] 2023-03-06 13:28
This doesn't have anything to do with the current thread but I am taking the opportunity to politely ask for some information for something I saw in an image above...
![image](https://user-images.githubusercontent.com/26836104/223123244-d88f49cc-d01e-4ea6-a4b8-416173e59e43.png)
How do you get the graphic icon with the image of the broadcaster? 
I only have the generic ones with the musical note symbol

73, Paolo

**Comment by softsyst** [comment] 2023-03-06 13:55
Hi Paolo,

you are using two different config files. This might be due to the fact that you start qirx sometimes directly from the exe (what I assume from your description). In that case, the qirxConsole.config is used.

If you start qirx from the installed icon, or from qirx.bat in the install directory, then usually qirx4.config is used as a config file.
The qirxConsole is necessary for the compatibility with the console version. If you change the parameter in the qirx.bat file to e.g. "Paolo", then a subdirectoy "Paolo" will be created with a Paolo.config file. 

It is always recommended NOT to start qirx.exe directly, due to this problem. qirx can have many data directories if this is needed. The (relative to the common base) data directory is the only parameter in the qirx.bat file of the GUI version. The console version can have more parameters, opening directly a certain receiving scenario.

The license is stored in the config file. If you use a different config file, you need to enter the license again. It had probably neither been lost nor not saved correctly.

In case you are not sure from which data directory you are working, you can click any time on the "Home" button on the top bar which will open directly an explorer window where the config file resides.

Maybe I should have named that config file qirxDefault instead of qirxConsole.

I hope this resolves the problem.

73,
Clem

**Comment by softsyst** [comment] 2023-03-06 14:02
Hi Paolo,

The logos are retrieved from muxes who send the so-called SPI information. In that case - after starting the mux - in the middle bar two green lamps start blinking. This means they are collecting the SPI info. After they stop blinking the logos should appear. However, not all muxes show the logos, and some have so many info that the collection takes half an hour. There is no general rule. 
If you are not sure, have a look at the Ensemble overview tab and look for a service named "EPG" or similar. There is also no general rule for that naming.

The logos are stored in the "SPI" directory tree, relative to the base directory.

73,
Clem

**Comment by andimik** [comment] 2023-03-06 15:52
> due to the fact that you start qirx sometimes directly from the exe

Let me guess, you started the scan during installation?

If yes, Clem, can you prevent that the setup routine launches Qirx?

**Comment by softsyst** [comment] 2023-03-06 16:18
You see me astonished. The setup routine doesn't start qirx. Here, this never happened. It starts during installation? really?

**Comment by PiNoise** [comment] 2023-03-06 16:42
> Hi Paolo,
> 
> The logos are retrieved from muxes who send the so-called SPI information. In that case - after starting the mux - in the middle bar two green lamps start blinking. This means they are collecting the SPI info. After they stop blinking the logos should appear. However, not all muxes show the logos, and some have so many info that the collection takes half an hour. There is no general rule. If you are not sure, have a look at the Ensemble overview tab and look for a service named "EPG" or similar. There is also no general rule for that naming.
> 
> The logos are stored in the "SPI" directory tree, relative to the base directory.
> 
> 73, Clem

I found a mux with EPG and I see now the two green LEDs flashing.... I let go for a few minutes and the beautiful icons appeared. Really cool QIRX !!!
![image](https://user-images.githubusercontent.com/26836104/223174790-d8c3d132-2e0b-4e00-be9c-d1703b0eb431.png)

**Comment by softsyst** [comment] 2023-03-06 16:48
Hi Paolo,

if they also transmit EPG (Electronic Program Guide), this is shown as well, in the EPG tab. 

73,
Clem

**Comment by PiNoise** [comment] 2023-03-06 16:48
> You see me astonished. The setup routine doesn't start qirx. Here, this never happened. It starts during installation? really?

Hi Clem,

I had made myself two Qirx launch icons on my desktop as I noticed that the one with the batch file often gave me the following error:
![error](https://user-images.githubusercontent.com/26836104/223176106-9f7e7410-b374-4f34-ab25-a05db9e2a586.jpg)

While the one directly from the EXE file worked correctly...

**Comment by softsyst** [comment] 2023-03-06 17:50
Then, best will be you work directly from the exe. Otherwise you would need to find out the reason why you get that tcp/ip error.
Now, as the issue has been clarified, I hope I can close it.

**Comment by PiNoise** [comment] 2023-03-06 18:03
Yes, issue closed. Thank you for all the valuable assistance these past weeks. Now I can finally dabble with the software in all its possibilities.

73, Paolo

**Comment by andimik** [comment] 2023-03-06 18:05
> You see me astonished. The setup routine doesn't start qirx. Here, this never happened. It starts during installation? really?

I can't tell you now as I'm currently working under Ubuntu. I know that lots of software installation routines launch the new program if the user wishes it. But if Qirx does not start it at all, forget my idea.

**Comment by softsyst** [comment] 2023-03-06 18:29
Thanks, Paolo, for your cooperation!

73, Clem

**Closed as completed by softsyst** 2023-03-06 18:29 UTC
