### ISSUE TITLE
Audio mute state

### ISSUE THREAD

**Issue by Frank-56** [softsyst/qirx_issues#138] opened 2024-01-23 12:24 UTC
When the audio is muted and it's been switched to another channel, the audio automatically gets unmuted. Qirx should keep the mute state.

**Comment by softsyst** [comment] 2024-01-23 13:01
No. QIRX should not keep the mute state. The described behavior is by design.

**Comment by Frank-56** [comment] 2024-01-23 13:12
Then it's not a good design and I did a lot of GUI design in my professional life. An optional setting in the config file would not only be sufficient but best. That's what I learned in 35 years working for big clients. You can compare this to the question "Do you really want to exit?". This should always be optional, too.

So please tell me wife that suddenly a sound appears by design at 10 in the evening when I forget to mute the Windows audio in general.

**Comment by softsyst** [comment] 2024-01-23 13:19
I close this one. Nothing to add here.

**Closed as completed by softsyst** 2024-01-23 13:19 UTC
Labels: not considered

**Comment by andimik** [comment] 2024-01-23 14:21
His suggestion is good, so I don't understand why it has been closed.

**Comment by softsyst** [comment] 2024-01-23 14:31
It has been closed as it will not be considered. See the tag. I will certainly not continue this discussion here.

**Comment by Frank-56** [comment] 2024-01-23 15:26
Clem, please do not forget: we are your customers who pay you for Qirx, even if the 20€ is only a recognition for your work. The way you answer is IMHO disrespectful against your customers. People are much more happy and satisfied if the know a reason for something. "The described behavior is by design" is not a good reason.

Hope you can close this issue permanently.

**Comment by softsyst** [comment] 2024-01-23 16:52
@Frank-56 
This issue has finally been closed. I thought about your notices ("please tell my wife..." etc etc) and came to the conclusion that QIRX is the wrong product for you. There are quite a number of excellent products which certainly suit your needs much better. 

As a result I will- for the first time - refund your payment which you - as a paying client -  rightly mentioned. 
At the same time I will delete you from my database. 
I hope this notice is respectful enough for someone with more than 35 years of experience (in whatever, certainly not in software development)!
