### ISSUE TITLE
UK BBC SPI logos not shown

### ISSUE THREAD

**Issue by mrwish7** [softsyst/qirx_issues#56] opened 2022-12-09 09:04 UTC
Hi Clem,

I've noticed that for the BBC National multiplex in the UK on 12B, SPI logos are transmitted and captured but QIRX doesn't show them. The data itself seems to be parsed, as I get PNG images and EHB files in the AppData\Local\qirx4\SPI\E1CE15 folder for the ensemble. The PNGs are all the BBC station logos, in multiple sizes.

Comparing with an ensemble that I've tested that does work (SWR BW S from Germany), the difference seems to be that for the SWR mux, the SPI folder seems to have an XML file which links the relevant logo to the respective service, and subfolders for each service with the correct PNG file inside. This is missing from the BBC mux SPI folder. I guess the BBC are doing something a little different and the mapping data isn't being parsed.

I can provide a raw recording of 12B if that would be helpful. Thanks for the great software!

<img width="916" alt="Screenshot 2022-12-09 090355" src="https://user-images.githubusercontent.com/37659188/206665079-23b19fea-6453-4d65-a502-06c1d162d14e.png">

(This shows an old logo, but the data in the folder has updated more recently with the BBC's updated ones)

**Comment by andimik** [comment] 2022-12-09 10:31
Additionally I would like to mention that Qirx is renaming these files (which contain the SId in general) by - for me - unknown reason. 

Qt-DAB does not rename them.

**Comment by softsyst** [comment] 2022-12-09 11:36
Hi mrwish7,

Thanks for this info. If the xml file is missing, something went wrong. 

I just repeated my BBC test with a file from 2021, it worked. Thus, a raw file from you of about three minutes would be most helpful. In my test file, the logos appear after about 2 1/2 minutes. 
BTW, the BBC is the only mux which I saw until now compressing their SPI info.

Here's the result of my test from last year:
![image](https://user-images.githubusercontent.com/51386375/206692266-734b789e-f56f-4d94-83eb-ec4cff1d67c2.png)

Clem

**Comment by mrwish7** [comment] 2022-12-09 12:11
That is interesting that they compress it!

Thank you, I have just recorded a 3 minute raw record from within QIRX for you to be able to investigate. Please let me know when downloaded as I will need to remove it from my Google Drive (running out of space :) ) - https://drive.google.com/file/d/195jRiYoYWkcJIMS88n1XEtE6XsNNlN3d/view?usp=sharing

Thanks,
Adam

**Comment by softsyst** [comment] 2022-12-09 12:49
Hi Adam,

thanks for replying quickly. I downloaded and tried the file. Sadly, after the three minutes it is still collecting data. If  a five minutes recording would be possible, I hope that would be sufficient. You could observe the E1CE15 directory and see when no more files are collected. 

If this should exceed the time for an uploadable raw file, another possibility would be that you zip the whole E1CE15 directory and send it to me, or upload it, together with the log file in C:\qirxLogging. But a raw file would be preferable, if possible.

Thanks for your cooperation!

Clem

**Comment by mrwish7** [comment] 2022-12-09 13:27
Hi Clem, I've just recorded for 5 minutes, and this time it has actually worked! It just takes around 4m30 for all of the data to download, so it actually just seems to be a length of time thing rather than a bug with QIRX. I wiped the old E1CE15 directory first, so maybe starting completely afresh helped in some way by wiping the multiple sets of partial data that were in the directory.

<img width="970" alt="2022-12-09" src="https://user-images.githubusercontent.com/37659188/206711364-7d1eaa06-c5c3-45d7-90a6-5ea33c59f6b0.png">

I've linked the raw recording file in any case just in case you wanted to look, plus I've attached my E1CE15 folder (now with the XML and individual service directories present) and QIRX log. https://drive.google.com/file/d/1YXGO9nUl6-DRp1-S2-T1kXn18E8O3lfF/view?usp=sharing

Thanks for your help,

Adam
[BBC_SPI_and_log.zip](https://github.com/softsyst/qirx_issues/files/10195167/BBC_SPI_and_log.zip)

**Comment by softsyst** [comment] 2022-12-09 15:40
Hi Adam,

thanks for your files and the good news. Your 5 minutes raw doesn't work here, as just about 4 seconds are missing. 

The info about the missing seconds can be extracted from the log file. The recording started with the following entry:
12/9/2022	14:08:54.079	qirx.DAB.mscDatagroupPack	***MOT Dir  transportId 35249, Type= MOTDirectory, ....

and it stops with that one
12/9/2022	14:13:57.220	qirx.DAB.dabDecoderPacketMOT	MOTState Complete

As you see, just four seconds missing. But never mind. I can see the info from your directory upload showing me the same as you posted here.

Their new logos are a nightmare (for qirx). All too tiny and unreadable. The old ones with the large numbers were much better. I think I have to search for a space on the GUI where to place bigger icons. And the EPG seems to work as well. Their EPG deserves the name, in contrast to most other stations here.

The fact that all old files remain in the directory, is still a SW glitch which I have to repair.

As a side note, the log file may be read user-friendly with the (free) app log4view.

Best,

Clem

PS In case there is no other problems, I'll close this one a little later.

**Comment by mrwish7** [comment] 2022-12-09 20:02
Hi Clem,

They do seem to have made the small logos very unreadable compared to the nicer older ones in your screenshot above.

Hmm, I've just been trying to get a record where it gets all the data and I'm having the problem again now. I'm deleting the E1CE15 folder in between each attempt in order to start afresh. After a few minutes of receiving 12B in QIRX, files stop getting written to the new E1CE15 folder, but I get no MOTState Complete message even after several more minutes of waiting (the example here is a 10 minute RAW recording), and the saved data is not parsed, so no logos appear in QIRX.

https://drive.google.com/file/d/1tZRpr31Q7LXgrywbynKdM9cQD5-dCC6l/view?usp=sharing

[SPI.zip](https://github.com/softsyst/qirx_issues/files/10197788/SPI.zip)

Thanks,

Adam

**Comment by softsyst** [comment] 2022-12-09 23:24
Hi Adam,

Thanks for the file. I can confirm your observation that the MOTState Complete indication is missing when receiving your file. The whole  MOT info seems to start newly after about 3 minutes. After this time span, the files downloaded all seem already to be present.
I'll have a look at it and get back to you when I found something. 
Strange that it sometimes seem to work.

Thanks for now,

Clem

**Comment by softsyst** [comment] 2022-12-10 20:04
Hi Adam,

The reason for the missing logos is the incomplete transmission. The MOT Objects which should arrive are sent in a so-called directory. All objects arrive, except one, which I could clearly identify with an extended logging.
The software shows the logos and the EPG only if all announced objects have been received.

I cannot see an error in the software.

Clem

**Comment by mrwish7** [comment] 2022-12-11 18:38
Thanks for investigating Clem, in that case it seems like the BBC are inconsistent in sending the full set of data, at least within a reasonable amount of time.

**Comment by softsyst** [comment] 2022-12-11 19:14
Hi Adam,

Time seems to be ok, the data with the one missing object is repeated again and again. 
The problem is that there is no other indication for completeness than looking whether all objects arrived (or I do not see it). Otherwise, I could try to process the incomplete data. Perhaps I'll try to look for repetitions.

If you could observe it, I would be grateful for a feedback in case you can see the logos. The time for completion should be less than three minutes, according to the log.

So far, I'll leave this open.

Thanks!

Clem

**Comment by mrwish7** [comment] 2022-12-11 21:55
Hi Clem,

Ahh I understand.

I've just checked again and it seems to be working tonight - they must be transmitting all of the objects as indicated again.

I've done another raw recording for you. As you will be able to see the logos load successfully after around 2m30 (and of course the XML data parses within the E1CE15 folder structure).

https://drive.google.com/file/d/1AWreddNwWoRpRO5hcTCGgEnS2sOAfWJh/view?usp=sharing

Thanks,

Adam

**Comment by softsyst** [comment] 2022-12-11 23:22
Hi Adam,

Yes, now it works is as it should. Thanks for the verifying file. It's always good to have actual test data.
Now at last I close that issue.

Thanks for a great cooperation!

Best,

Clem

**Closed as completed by softsyst** 2022-12-11 23:22 UTC
Labels: bug
