### ISSUE TITLE
No valid info for transmitting location

### ISSUE THREAD

**Issue by superblyb** [softsyst/qirx_issues#82] opened 2023-04-05 17:38 UTC
For a long time, QIRX is not showing Ittervoort as the location from which I am receiving 12C NPO (from the Netherlands) at my location near the city of Venlo.
So, I am living near the city of Venlo, and I am receiving a strong signal for 12C NPO, but QIRX is only showing far away transmitting locations, and often no transmitting location at all.
As shown in the attached image, the CNR value is 30,7, where the strongest strength shows only a value of 0,060.

![12C](https://user-images.githubusercontent.com/129985820/230159099-fe0bf98e-1b58-4263-a744-9fa6ef810117.jpg)

**Comment by andimik** [comment] 2023-04-05 18:12
Info for Clem: 

https://ukwtv.de/cms/niederlande-dab/limburg-dab.html

ch | Site | ERP [kW] | Pol. | planned | TII | Remarks
-- | -- | -- | -- | -- | -- | --
12C | Venlo | 0,1 | v |   | 0211 |  
12C | Ittervoort/Alticom Toren | 5,6 | v |   | 0311 |  
12C | Sittard (Industriestraat) | 1,2 | v |   | 0313 |  
12C | Heerlen (De Beitel) | 1,2 | v |   | 0310 |  
12C | Maastricht/Cellnex Toren | 0,8 | v |   | 0210 |  
12C | Eys/Cellnex Toren | 1,5 | v |   | 0306 |  

So he expects to see 0311 in the recording.

**Comment by softsyst** [comment] 2023-04-05 18:21
Thanks, superblyb and also andimik for this info.

@suberblyb, for an investigation I would need a raw file of about one minute or so. Please be so kind and make a recording and an upload to a dropbox or similar. You might post the download link here or to my email address which you find on my website.

Then I hope to be able to check why it is not showing up in the TII list.
Thanks for cooperation.

Best,
Clem

**Comment by WIHDIA** [comment] 2023-04-05 18:42
Odd as Ittervoort is perfect here in central Belgium with 2 stacked antennas pointing that direction.  Lowering LNA? Antenna problem? 

![afbeelding](https://user-images.githubusercontent.com/53539654/230174548-32a1fbd0-fccc-4b47-89a5-eb76faf12b23.png)


73

Herman
BELGIUM editor f[mlist.org](https://www.fmlist.org)
[My logblog](https://wijnants.info/fmdx/)

**Comment by superblyb** [comment] 2023-04-06 03:14
Thank you for your comments. I am new to both github and dropbox, so I hope the following links will be functional.
https://www.dropbox.com/s/cfqo1z5uba86h27/GNSS_2023_04_06_04_22_37.txt?dl=0
https://www.dropbox.com/s/4bpeozi4c24i2gh/2023_04_06_04_22_37_2048000_fHz227360000.raw?dl=0
:)

**Comment by softsyst** [comment] 2023-04-06 09:58
Thanks for the recording. I confirm this to be a bug in qirx. I can reproduce the error and will get back here when I had a look. Strange that Herman observes the correct behavior.

BTW and off-topic here, the text file would not have been necessary. It contains the GPS info in case you have a GPS connected. Some people make recordings when driving around. Then, you can see you location on replay.

**Comment by superblyb** [comment] 2023-04-06 14:05
I might add that even when using a radio device, 12C is often skipped when scanning, and this is often also the case when scanning with Dabplayer , welle.io and qt-dab. However, this only happens when I have my yagi antenna connected. 
On the contrary, when I use a simple indoor telescope antenna, 12C is often found as the only multiplex when scanning.
And with my omnidirectional outdoor antenna, the transmitter in Venlo with a power of 0.1 kW will be detected, it is at a distance of several kilometres from my location, and in the opposite direction of my yagi antenna.
My yagi antenna is pointed towards Liège, which is almost the same direction as Ittervoort.
However, with my omnidirectional antenna connected, Ittervoort will not show up either.

**Comment by softsyst** [comment] 2023-04-06 16:00
Hi together,

Some investigations were made on @superblyb's raw file. I added the "bug" tag, but this bug is NOT the fact that the TIIs belonging to the strong transmitter(s) are not indicated. Let me explain:

@andimik's table shows that the two expected TIIs are 2/11 and 3/11, as is confirmed with a look at the map, where as usual the grey ones are not received, only the colored ones:


![TII Situation](https://user-images.githubusercontent.com/51386375/230430335-b3b564f0-5b8d-4fe5-91ee-fb539eb5fb76.jpg)

The green circle is Venlo, the location of @superblyb, The 2/11 (orange circle) is a local mux with low power, the 3/11 (orange circle) has higher power and might therefore be as strong as the local Venlo mux. 

This is a classical TII collision. Same Sub Id, different Main Id. It cannot be resolved by the software. I explain this in the [two-part TII Tutorial](https://qirx.softsyst.com/QIRXTIICollisions?sequenceNo=0), thus I should have recognized the situation immediately (but the tut has been made some time ago).
**Thus, the non-recognition of 2/11 and 3/11 is not a bug, but a correct feature.**

Now comes the bug. On the qirx GUI, there is a checkbox "Show Collisions for Sub Id". The selection of Sub Id 11 should show all possible combinations for different Main/Sub combinations in the data stream, which it doesn't. A bug.

Another indication that both probable transmitters 2/11 and 3/11 are received is shown in the CIR window (please ignore the icons in the top bar, they belong to the Debugger):

![CIR](https://user-images.githubusercontent.com/51386375/230426101-a689fbdd-43bc-4926-9b94-9d5b0d78fe1b.jpg)

The three unambiguously received transmitters 3/13, 3/6 and 2/10 are indicated nicely above their corresponding peaks. But the two largest peaks have no indication. Most probably these are the ones belonging to the colliding 2/11 and 3/11.
The distance between the two (no signal delay assumed) is shown as about 25km, which is confirmed by a short measurement in Google-fu.
And, last not least, **Herman** has no problems as the 2/11 with its 100W (right click the icon: Info) is just too weak for his location.

That's it for now. Again, for me some work to do, as the collision resolver aid should work.

**Comment by softsyst** [comment] 2023-04-07 17:11
Here comes just some information how the TII collisions will be treated in the coming version. As the example I chose the file of @superblyb.

In the recent posting I mentioned the "Show Collisions for SubId" drop down box, where a colliding SubId (i.e. where different Main Ids have the identical Sub Id) can be selected. This will again work as in previous versions, the error was rather trivial. 

However, a user experiencing strong transmitters just not showing their TII Ids had been left in the dark about on which SubId is happening the collision. This knowledge is necessary to select one of the 24 possible ones of the drop down box. Of course, all could be tried, but this is rather tedious and not a comfortable solution.
Therefore, the new version will get some additional help to find it out quickly. 

Please have a look at the following screenshot. 

![TIICollision](https://user-images.githubusercontent.com/51386375/230645197-8aee9035-b8d6-499a-a6ca-2d97fbe1aa4d.jpg)

In the red circles in the CIR spectrum and the TII List you notice a Main Id of 99. This is a newly introduced pseudo-Id indicating that the corresponding Sub Id has a TII Collision, and the proper Main Ids can in principle not be determined in the software.

But now you are able to select in the above mentioned combo box the SubId where the collision happens. If you do so with the now known SubId of 11, this will look like in the following picture (red square):

![TIICollisionAllpossible](https://user-images.githubusercontent.com/51386375/230646025-4dfa76bc-d944-43e3-af3c-e554e17b013f.jpg)

The program will list all possible Main/Sub combinations which are possible with the collision. Sadly, it has no possibility to find out which four of the five possible carriers are the correct ones. Here it is rather simple to find out, as only two of the five have already an entry in the database, giving a certain probability that these are the ones which are looked for. But the final decision is up to you, the user, from properties like CIR distances, transmitter power and the like.

You might also note that all five possible Main/Sub combinations are indicated in the CIR spectrum. Why they are in the middle of the two relevant carriers is another story which will soon be covered in another - third - part of the TII Collision tutorial. This description here is part of  the content, in a nutshell.

**Comment by WIHDIA** [comment] 2023-04-07 17:19
Hi Clem,

This a great new feature and I'm looking forward to test this on 9B and 12C. I struggled with finding the collisions and didn't see the bug in the system.

73

Herman
BELGIUM editor f[mlist.org](https://www.fmlist.org/)
[My logblog](https://wijnants.info/fmdx/)

**Comment by superblyb** [comment] 2023-04-27 15:26
The 99 value works nicely with 4.08, and both 2-11 Ittervoort and 3-11 Venlo are now being shown on the map. Thx :)

**Comment by softsyst** [comment] 2023-04-27 15:51
Thanks for your nice comment! I'll close this. Of course, if necessary, it can be re-opened again.

**Closed as completed by softsyst** 2023-04-27 15:51 UTC
Labels: bug
