### ISSUE TITLE
The AGC is too nervous in case of DAB

### ISSUE THREAD

**Issue by schluckspecht** [softsyst/qirx_issues#70] opened 2023-01-17 17:42 UTC
When I am listening to NDR DAB+ on channel 10a I have the problem that the AGC is very nervous, so I have to disable it. If I set it to "control manually" and to the suitable value , the SNR is always 16 db, but if the AGC is set to automatic, the AGC is changing the whole time, the SNR is changing from 16 db to less than 11 db and audio is lost periodically. Using the "filter" function with 1900 kHz bandwidth and filter order 900 helps a little bit, but  even with that the audio is lost sometimes. Perhaps this is caused by the strong DAB+ station in Münster on channel 9b, but I do not know:
Software: QIRX 3.2.2. with "rtl_tcp" last version on a raspberry Pi 4 and a "RTL283U R860T" dongle from "rtl-sdr.com"
Windows 10 with last updates. Antenna: An outdoor vertically polarized VHF 3 dipol.

**Comment by softsyst** [comment] 2023-01-17 20:41
Hallo schluckspecht,

your Tuner is R860T? Is that correct? Did you have the opportunity to check with other dongles, or receivers? Could you make a raw file that I could have a look?
Is this behaviour only on 10A or does it show it generally?

Thanks for now!

**Comment by schluckspecht** [comment] 2023-01-18 17:19
Sorry, but I do not have other dongles, or receivers. The PC does not matter, the bahaviour is the same on 2 different PCs. I can receive 5 DAB channels, but the other 4 are very strong (WDR Münster Baumberge = 11d, Münster Stadt = 5c, 9b and 9d) , only the 10a is weaker, and only there I can see that the nervous AGC makes such problems. But even for the strong stations the AGC is always trying to "optimize". So even for the channel WDR 11d, that does not have a neighbour channel, the AGC is nervous, but because of the signal strength and quality  it does not cause problems.  If AGC is disabled and the amplification is set correctly manually, audio will never be dropped. In case of AGC on this happens all few minutes. and all few seconds you can see that the SNR is going down. (In the video you can see that, but there was not an audio drop. (Murpheys law ;-)  How can I make a raw file?

https://user-images.githubusercontent.com/84860874/213250188-a381b9fd-c289-49be-94cb-400449ec1d64.MOV


https://user-images.githubusercontent.com/84860874/213250210-545327df-945f-4dba-9765-c90fb1e58a7a.MOV

![Dongle](https://user-images.githubusercontent.com/84860874/213253738-44fd6217-09fb-401a-9e7c-9dc710953d0d.jpg)

**Comment by softsyst** [comment] 2023-01-18 21:24
Thanks for the picture and the videos. A raw file would be good. You find the raw recorder in the "Frontend" pane, upper left GUI part, "Recorder" tab. Here:

![image](https://user-images.githubusercontent.com/51386375/213296608-e3955af0-710a-487a-9e41-4588d2cf01a4.png)

The file is stored in the "Raw" directory, relative to the "Home" dir, which you reach by clicking on the "Home" button in the top row.

One minute will create about a 250MB raw file, which you could upload to a dropbox or similar.
BTW do you know how the R860T tuner differs from the R820T?

**Comment by schluckspecht** [comment] 2023-01-19 20:44
Do you know how the R860T tuner differs from the R820T? --> No, I do not know.
I do not have dropbox or similar, directly here did not work :-(. (File size too big)

**Comment by softsyst** [comment] 2023-01-19 21:30
Directly will not work anywhere with these sizes. That is the reason for dropbox or wetransfer or similar.
Anyway, I'll try to reproduce the behavior. The R860T should behave identical to the R820T2 which I have here, as I learnt in the meantime.

**Comment by schluckspecht** [comment] 2023-01-21 12:53
I saw this nervous AGC only for the weaker NDR and the very strong WDR multiplex. Perhaps the root cause is, that WDR and NDR have here two overlapping transmitters. Of course, DAB was made to handle a single-frequency network, but this is the difference between the channels 5c (Germany multiplex 1), 9b (NRW multiplex) and 9d (Germany multiplex 2) where only one transmitter is dominant and where nearly no other stations or reflections are visible, and NDR or WDR. In case of NDR it is Dörenberg plus Lingen, in case of WDR it is Baumberge and Schöppingen. See the channel impulse response of diagram of NDR. Even on FM the transmitter Lingen is very strong, because there are no hills between Lingen and Münster (of the Teutoburg Forest)
![NDR](https://user-images.githubusercontent.com/84860874/213867628-ad9f3b87-e1e0-4d55-b61e-8e68bc6a2901.png)
![NDR-locations](https://user-images.githubusercontent.com/84860874/213867766-5aa211ac-07b8-47d0-8186-944cff85dadd.png)

**Comment by rf-oldie** [comment] 2023-02-03 19:15
I guess you've selected a bandwidth of at least 2000 kHz in the R820T Tab.
Try to set it to 1500 or 1400.
Maybe this solves the problem

**Comment by schluckspecht** [comment] 2023-02-03 21:20
The bandwidth was set to 1820 kHz. With that I had the best results. Because DAB hat a bandwidth of 1536 kHz, the filter must be wider than this minimum. But even with 1600 or 1700 I had problems that the software did not sync to the signal, I think, that the filter causes phase shift problems at the DAB signal boarders if these are so close to the filter boarders.

**Comment by rf-oldie** [comment] 2023-02-04 00:17
From my experience a bw of 1500 is no problem. Due to the delta-QPSK a phase shift does not affect the demodulation. Even some DAB transmitters have a nonlinear phase shift...
Best results with strong adjacent channel carriers I have with a setting of 1500, even if the corner frequencies are attenuated a bit:
![Spectrum](https://user-images.githubusercontent.com/106614376/216733524-852d0891-5952-48c3-83d6-33e9738e9be1.jpg)


Seemed to me that a strong adjacent signal might be the problem for the nervous AGC... 
![Spectrum1](https://user-images.githubusercontent.com/106614376/216733547-954f6443-c342-4d6c-9c33-aa369db6449b.jpg)

**Comment by softsyst** [comment] 2023-02-19 00:52
4.0.6 and higher use the hardware-based AGC of the dongle. Please check if the AGC is less nervous.

**Comment by schluckspecht** [comment] 2023-02-23 16:40
Yes I would test it, if I would not have to buy a licence and then if it does not the licence is for the waste paper basket ;-). The 3.x was free, the 4.x costs money.

**Comment by softsyst** [comment] 2023-02-23 17:31
You can test it very well on a Demo license, if you wish. And the 3.x WAS not free, it IS free.
Anyway, thanks for your kind input!

**Comment by schluckspecht** [comment] 2023-02-23 21:03
The 3.2.2 starts, the 4.0.7 crashes that way, that the blue arrow switches back to off after some seconds, But that is fake news, in the logging you can see that still ip packets are send. But nothing happens. Very often the application crashes, that you can not press any button of the software any more, you have to kill it with the task manager. The config is the same as in case of 3.2.2.

Here the log in the rtl_tcp output:
istening...
Use the device argument 'rtl_tcp=192.168.29.178:1234' in OsmoSDR (gr-osmosdr) source
to receive samples in GRC and control rtl_tcp parameters (frequency, gain, ...).

client accepted! DESKTOP-DKML9LK.fritz.box 59914
Allocating 15 zero-copy buffers
ll+, now 1
ll+, now 2
ll+, now 3
ll+, now 4
ll+, now 5
ll+, now 6
ll+, now 7
ll+, now 8
ll+, now 9
ll+, now 10
ll+, now 11
ll+, now 12    -----> and further and further, nothing happens.

In case of 3.2.2
Use the device argument 'rtl_tcp=192.168.29.178:1234' in OsmoSDR (gr-osmosdr) source
to receive samples in GRC and control rtl_tcp parameters (frequency, gain, ...).

client accepted! DESKTOP-VPL28PI.fritz.box 51487
Allocating 15 zero-copy buffers
ll+, now 1
ll+, now 2
ll+, now 3
ll+, now 4
ll+, now 5
...
...
ll+, now 75
ll+, now 76
set bias tee 0
set sample rate 2048000
ll+, now 77
ll+, now 78
set gain mode 1
set agc mode 0
set bias tee 0
set freq 209936000
ll-, now 0
set freq correction -2
set tuner gain by index 13
set gain mode 1
ll+, now 1
set agc mode 0
set freq 209936000
set freq correction -2
set freq 209936000
ll+, now 2
ll+, now 3
...
...
ll+, now 26
ll+, now 27
ll+, now 28
ll+, now 29
set tuner gain by index 14

**Comment by schluckspecht** [comment] 2023-02-23 21:05
![image](https://user-images.githubusercontent.com/84860874/221029960-5432af88-29c9-41c8-bbb1-e748a27f3914.png)

**Comment by schluckspecht** [comment] 2023-02-23 21:05
![image](https://user-images.githubusercontent.com/84860874/221030060-42491858-5ca9-436f-a226-def5a1897f15.png)

**Comment by softsyst** [comment] 2023-02-23 21:33
Could you send me a log: C:\qirxLogging ?

**Comment by schluckspecht** [comment] 2023-02-24 18:43
[Version-4.07-not-workingqirx.logqirx.log-2023-02-24--20-03-04.txt](https://github.com/softsyst/qirx_issues/files/10828028/Version-4.07-not-workingqirx.logqirx.log-2023-02-24--20-03-04.txt)
So, I found something strange. Although the IP of the raspberry Pi with the SDR dongle and the rtl_tcp daemon is configued correctly in the GUI (see above), configured the same way as in the 3.2.2. example, where the IP = 192.168.29.178 can be connected and the device is set up. In case of 4.07 it seems to try several times.

[Version-3.22.correctlyworking-qirx.logqirx.log-2023-02-23--21-43-28.txt](https://github.com/softsyst/qirx_issues/files/10827893/Version-3.22.correctlyworking-qirx.logqirx.log-2023-02-23--21-43-28.txt)

**Comment by schluckspecht** [comment] 2023-02-24 19:12
[tcpdump-der-nicht-laufendfen-Verbindung.zip](https://github.com/softsyst/qirx_issues/files/10828045/tcpdump-der-nicht-laufendfen-Verbindung.zip)

**Comment by schluckspecht** [comment] 2023-02-24 19:14
The tcpdump during that broken attempt, made at the same time. As you can see, the problem is not on the IP layer
[tcpdump-of-the-not-working-connection.zip](https://github.com/softsyst/qirx_issues/files/10828067/tcpdump-of-the-not-working-connection.zip)

**Comment by softsyst** [comment] 2023-02-24 21:54
No surprise here, as the current version does no longer work with the old rtl_tcp.exe, but needs the rtl2_tcp.exe from the distribution. It allows for a selection in case more than one RTL-SDR hardware is present. The necessary driver is available from old-dab's GitHub site, but needs to be compiled for Linux use. The necessary back-channel listens to a port one larger than the forward-channel. Thus, the connection to port 1235, requested from qirx, fails with the rtl_tcp used on Linux.

Thanks for the log files. 

What about the crashes?

**Comment by softsyst** [comment] 2023-03-05 19:19
As there are no new entries, I close this one. Please re-open if necessary.

**Closed as completed by softsyst** 2023-03-05 19:19 UTC

**Comment by schluckspecht** [comment] 2023-03-07 17:37
The version 4.0.7 works perfectly. (Therefore I have already ordered the permanent licence ;-) )
I can receive the NDR the whole time without any drops.
I made some filter settings as a trial, but they do not have any impact, except the bandwidth is too small. Even with the deault values (ca 2 MHz) it works perfectly. 
![image](https://user-images.githubusercontent.com/84860874/223506822-76cec217-4a1c-46b2-9c61-489ec4b7869b.png)


Sadly this rtl2_tcp crashes very often on a raspberry pi 4.  It would be nice, if the "old" rock solid stable rtl_tcp would be supported as in V3.2.2
Last version from https://github.com/old-dab/rtlsdr .
It crashes permanently, when e.g. the tcp stream is stopped by clicking the red x in the Qirx tool or by terminating the Quix tool. That makes no sense.

set freq 176640000
set freq 178352000
set freq 209936000
set bias tee 0
Tx thread terminated, do_exit:0
Signal (2) caught, ask for exit!
Rx thread terminated, do_exit:1
Signal (2) caught, ask for exit!
Control thread terminated
all threads dead..
listening on port 1234...
listening on port 1235...
client accepted!
control client accepted!
set bias tee 0
**Speicherzugriffsfehler**
pi@raspberrypi:~/rtlsdr/build $

**Comment by softsyst** [comment] 2023-03-08 00:05
Glad you are content with the 4.0.7. 

BTW, rtl2_tcp issues do in no way belong to this thread. So, of course you might feel free to criticize in in a non-insulting way, but please in a different thread. Mixing topics in  one thread is always a bad idea.

Thanks,
Clem

**Comment by schluckspecht** [comment] 2023-03-08 17:44
But I am not the only one wishing back the good old stable rtl_tcp. See https://github.com/softsyst/qirx_issues/issues/57. And because this is a precondition to fix the AGC problem by switching to Qirx 4.07, I think this is direct part of the discussion. Therefore is it possible to support rtl_tcp too? Supporting a standard tool like rtl_tcp would certainly increase the acceptance of a software instead of supporting a rather proprietary protocol. Further rtl2_tcp is not supported by other common SDR software, so you have to switch the processes.

**Comment by softsyst** [comment] 2023-03-08 19:32
I know very well that there are requests to support the old rtl_tcp. It would be good to open a new issue. The argument with the compatibility (not "proprietary", as it is Open Source and has been changed from the original rtl_tcp since long, for very good reasons). I am currently investigating it.

The poster of #57 was happy with the rtl2_tcp. To bring his posting in connection with a possible instability of rtl2_tcp, is misleading. His problem was the missing binary of rtl2_tcp in Linux, which he then produced himself, and was very happy with the product. Nothing at all about "instability".
Quote:

> I've just compiled rtl2_tcp from that source on the Pi and can confirm that it works very well. I find the channel tuning to be quick for me, and the reception is very stable (Pi4 connected to wired network, Windows laptop running QIRX connected to Wifi.).

What is the origin of the binary of your unstable rtl2_tcp?

**Comment by schluckspecht** [comment] 2023-03-08 20:00
I will create a new request.

The origin is the last version from https://github.com/old-dab/rtlsdr, then compiled on the raspberry PI. I did it as described , was compiled and build. I took a fresh image on the raspberry Pi to prevent interferences. The RTL dongle was blacklisted from autodetection as necessary. 

All updates were installed and libusb1.0 was installed too.

git clone https://github.com/old-dab/rtlsdr
cd rtl-sdr/
mkdir build
cd build
cmake ../
make
sudo make install
sudo ldconfig

Obviously rtl2_tcp runs without problems as a daemon , as service in the background. Since I created a service and made it with systemctl enable permant, it seems to run (since yesterday). I created this service for that. 

pi@raspberrypi:/etc/systemd/system$ cat rtl2_tcp.service    
[Unit]                                                      
Description=Software Defined Radio TCP Server               
Wants=network.target                                        
After=network.target                                        
                                                            
                                                            
[Service]                                                   
ExecStart=/usr/local/bin/rtl2_tcp -a 192.168.29.178 -p 1234 
Restart=always                                              
                                                            
                                                            
[Install]                                                   
WantedBy=multi-user.target                                  

The reason I did not start it as daemon was, that I had to switch between rtl_tcp and rtl2_tcp manually because my other SDR software radios are incompatible to rtl2_rcp. And then running in a console is easier.   Of course I became curious and tried console again: After some station switches crash.    Speicherzugriffsfehler

**Comment by softsyst** [comment] 2023-03-08 21:56
Thanks for info!

To verify the problems, I made a test on my debian11, after a build according to your sequence. It works nicely without crashes, as a commandline version, no daemon, with a single RTL-SDR dongle. QIRX 4.0.7 from the current download.
The very latest version of old-dab is the 0.9.6.6, of yesterday or even today.
Maybe you give it a try, in case you didn't already.

It would be best to discuss these issues directly with old-dab, in his GitHub. I am not the creator of the SW.
One more question: the current build creates also a rtl_tcp. Did you try perhaps with one of your other SDRs whether that one works? Or with the 3.2.2, which I do not have currently running here?
