### ISSUE TITLE
Starting QIRX

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#20] opened 2021-10-10 05:23 UTC
Sometimes, not always, QIRX takes quite a long time to start of shut down. Sometimes after starting it up there's no detection and I have to shut down and start again the Rx to get it running. Very occasionally I need to restart QIRX to get it running. It often happens after a first use when rebooting the pc, but then again I can also happen after running the pc for hours and having run and closed QIRX often. It might of course hardware thing related to my pc. This is of course nothing more than just a bit of a nuisance.

**Comment by softsyst** [comment] 2021-10-24 13:04
I assume that the search for a GNSS COM port on startup could be the culprit. I'll make a change in the next version to see if this is the cause.

**Comment by softsyst** [comment] 2021-10-25 09:15
I close this issue, as it seems to be fixed.

**Closed as completed by softsyst** 2021-10-25 09:15 UTC
