### ISSUE TITLE
Missing scrollbar when map is active

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#40] opened 2022-07-27 07:02 UTC
Whenever I activate the map, there is no scroll bar on the right, so I cannot change the channel or the service.

![grafik](https://user-images.githubusercontent.com/24510556/181182455-51bb9ace-a57c-49c5-819b-5801f03c2fca.png)

After closing the map, I see the rest.

**Comment by andimik** [comment] 2022-07-27 07:11
Additionally, some parts are hidden in standard view due to the missing scroll bar.

![grafik](https://user-images.githubusercontent.com/24510556/181183783-acce2dbf-0bfe-4ebe-a2d3-60a49f265646.png)

In order to see all entries in "Audio" tab, I need to reduce radically the receiver window.

![grafik](https://user-images.githubusercontent.com/24510556/181183985-8964d179-66a6-42fa-a758-3e46cb924916.png)

**Comment by softsyst** [comment] 2022-07-31 22:47
Andreas,

could you occasionally check with the 4.01 if that's ok in your opinion? A complete vertical scrollbar on the right spanning the frontend and the demodulator section brings many problems, so I left it out. The DAB parts now should all have vertical scrollbars.

**Comment by andimik** [comment] 2022-08-01 06:17
Will test it next week only.

**Comment by andimik** [comment] 2022-08-05 09:11
Thanks Clem, I've tested 4.01 today

> A complete vertical scrollbar on the right spanning the frontend and the demodulator section brings many problems, so I left it out.

Really?

Some parts are still invisible. My laptop has a resolution of 1366x768, btw. 

This is the screenshot without changing the sub-window sizes.

![grafik](https://user-images.githubusercontent.com/24510556/183041762-b4106e7c-108b-4da9-90f2-a501bd70ce8a.png)

You have added some (= not all) scroll bars in each subwindow, which is OK for me. 

But some subwindow scrollbars disappear again:

![grafik](https://user-images.githubusercontent.com/24510556/183042135-8229f094-01ce-40a5-8882-6e3c07a9d660.png)

Not even a chance to scroll down to the SLS (which is below of all the DLS information).

And some have very tiny sub-sub scrollbars

![grafik](https://user-images.githubusercontent.com/24510556/183040786-99407ab8-c4e8-41cf-91f5-435b1f240094.png)
green: expected place scrollbar
red: in fact very tiny scrollbar

Hint: You are wasting much of space in my opinion:

- "Receiver 1/2/3" (you need to untick the 2 and 3 in the option in order to get this bar invisible)
- DAB Display update rate (integrate somewhere else)
- options for constellation, TII, etc should be moved to an option dialogue 

And there is a square without any function.

![grafik](https://user-images.githubusercontent.com/24510556/183041584-e2570a17-9e92-4e3d-90ca-87e83500f63d.png)

**Comment by softsyst** [comment] 2022-08-05 18:44
> Thanks Clem, I've tested 4.01 today

Thanks, Andreas, for your testing and commenting in this elaborate way, which is much acknowledged.

However, I cannot agree with all of your suggestions. Please keep in mind that the qirx GUI has not been designed to work perfectly also on the smallest possible screen. With a fairly complex GUI like this one, there must be some compromises for smaller screens.

With respect to your screen size: There will be definitely more space for the DAB info if you collapse the frontend part. That is its main intent. And perhaps it would be useful to undock at least the map. Although of course I see your point to show the suggested startup screen.
> 
> > A complete vertical scrollbar on the right spanning the frontend and the demodulator section brings many problems, so I left it out.
> 
> Really?

Yes, really. Won't go into more detail here, this would be very WPF-specific.
> 
> Some parts are still invisible. My laptop has a resolution of 1366x768, btw.
> 
> This is the screenshot without changing the sub-window sizes.

This screen is of course intended to be adapted by the user to a specific taste and needs. Its intent is NOT to display everything also on a rather small screen. 
> 
> ![grafik](https://user-images.githubusercontent.com/24510556/183041762-b4106e7c-108b-4da9-90f2-a501bd70ce8a.png)
> 
> You have added some (= not all) scroll bars in each subwindow, which is OK for me.
> 
> But some subwindow scrollbars disappear again:
> 
> ![grafik](https://user-images.githubusercontent.com/24510556/183042135-8229f094-01ce-40a5-8882-6e3c07a9d660.png)
> 

Will check this one.
> Not even a chance to scroll down to the SLS (which is below of all the DLS information).

The slideshow images now scale w/r to the window size. Thus, to remain larger, either the DAB should get more space by collapsing the frontend section or the tab should be undocked. IMO, this is the better solution than to display partial images.
> 
> And some have very tiny sub-sub scrollbars

Yes, this cannot be changed. The scrollbar size is set by the system in relation to the whole content size to be scrolled. Like in every correct scrollbar.
Btw, same can happen in the EPG window.
> 
> ![grafik](https://user-images.githubusercontent.com/24510556/183040786-99407ab8-c4e8-41cf-91f5-435b1f240094.png) 
green: expected place scrollbar red: in fact very tiny scrollbar
See above remark
> 
> Hint: You are wasting much of space in my opinion:

> 
>     * "Receiver 1/2/3" (you need to untick the 2 and 3 in the option in order to get this bar invisible)

This bar is there on purpose, to allow an easy switch between the receivers. I see no reason why it should be wasted space.
> 
>     * DAB Display update rate (integrate somewhere else)

Agree on that one.
> 
>     * options for constellation, TII, etc should be moved to an option dialogue

Disagree
> 
> 
> And there is a square without any function.
> 
> ![grafik](https://user-images.githubusercontent.com/24510556/183041584-e2570a17-9e92-4e3d-90ca-87e83500f63d.png)

Also agree, it's not a bug, but not nice!

**Comment by softsyst** [comment] 2022-08-14 19:23
See the new V4.0.2. Hope it's ok now!

**Comment by softsyst** [comment] 2022-08-23 20:10
No further comments, thus I hope it's ok now. I close this issue. If necessary, feel free to re-open it.

**Closed as completed by softsyst** 2022-08-23 20:10 UTC
Labels: bug

**Comment by andimik** [comment] 2022-08-27 06:01
Yes, the full screen map is now even better (honestly).

Just a suggestion: The icon "show map" only switches the map on. When you want to close it, you need to press a different button (the "x"). 

Why not use a toggle icon "show/hide map"

BTW: There is already a toggle function, but I guess this is a bug. When you press the "show map" several times then the ADS-B column appears several times.

![grafik](https://user-images.githubusercontent.com/24510556/187017207-627a884b-41c1-4b0e-bd03-e70438a73987.png)

**Comment by softsyst** [comment] 2022-08-27 10:29
Thanks, Andreas, for reporting this bug. I entered it as an open issue.
