### ISSUE TITLE
Crash in DAB mode...

### ISSUE THREAD

**Issue by PiNoise** [softsyst/qirx_issues#77] opened 2023-02-23 16:08 UTC
Hi Clem!

From some QIRX release (v4.05/4.07) I always have strange anomalies that for me make the software unusable by crashing...
These are my steps (in Windows 10 64 bit and AirSpy R2/RTL-sdr).
* clean installation and removing previous installation
* startup by running "qirx.bat"
* In the configuration I select only for AirSpy and enter the personal license.
* close and reboot
* "not connected airspy-tcp" already appears on the RX1 line.
* if I select DAB and launch with blue triagle icon the program crashes immediately
* if I select AM/WFM/FMN it starts correctly
* same situation if I use an RTL-SDR

I enclose detail that appears in my AirSpytcp screen...

**_airspy_tcp, an I/Q data server for Airspy receivers
version 0.14 for QIRX, 04.10.2021
Airspy library version 1.0.9
Parameter d not supported.
Bit width 1 selected.
Set LNA AGC 1 succeeded
Set Mixer AGC 1 succeeded
listening...
Use the device argument 'rtl_tcp=127.0.0.1:1234' in OsmoSDR (gr-osmosdr) source
to receive samples in GRC and control parameters (frequency, gain, ...).
client accepted!
start rx
set bias tee 0
set sample rate : 4096000
Set sample rate 4096000 succeeded
set gain mode 1 : not implemented
set bias tee 0
set freq 88300000
set freq correction ppm*100: 0
set tuner gain by index 11
set gain mode 1 : not implemented
set freq 88300000
set freq correction ppm*100: 0
set tuner gain by index 12
set freq 178352000
set tuner gain by index 11
set tuner gain by index 10
set tuner gain by index 9
set tuner gain by index 8
set tuner gain by index 7
set tuner gain by index 8
set tuner gain by index 9
set tuner gain by index 8
set tuner gain by index 9
set tuner gain by index 8
set tuner gain by index 9
set tuner gain by index 8
set tuner gain by index 9
set tuner gain by index 8
comm recv bye
stop rx
listening...
Use the device argument 'rtl_tcp=127.0.0.1:1234' in OsmoSDR (gr-osmosdr) source
to receive samples in GRC and control parameters (frequency, gain, ...).__**

Thank you for your help and suggestions,
Paolo R.

**Comment by softsyst** [comment] 2023-02-23 17:40
Hi Paolo,

Here my Airspy Mini works without problems. The output from your driver exe looks good, until the "sudden death". The app had communicated properly with the airspy_tcp.exe.
As I cannot reproduce the problem here, would it be possible for you to send me a log file? It should be stored in the directory C:\qirxLogging. Maybe I can find out something from there.

Also strange that it happens with RTL-SDR dongles as well.

Sorry that you are having problems.

73,
Clem

**Comment by PiNoise** [comment] 2023-02-24 08:10
Thank you Clem for your immediate response.

Yes, I'm very sorry I can't use it for a long time, I had become very fond of it!
I tried different things always with the same result. 
I have uninstalled and reinstalled it several times. Unfortunately, here I have only one laptop and no way to test it on a second one. Could it be some block imposed by recent Windows updates, firewalls and whatever else we use for protection?
But why is the crash only happening for DAB and not the other modes?

No problem to send you the logs files. I still have four from yesterday's last tests. Can I enclose them here or send them to you by personal email?

Thank you for your time in development and assistance. Good work.

73, Paolo

**Comment by softsyst** [comment] 2023-02-24 11:28
Ciao Paolo (I assume you're in Italy?),

please send me the log files per PM. I'll have a look.
DAB uses way more resources than the other modes. But of course, a crash should not happen.

Thanks for your cooperation!

73,
Clem

**Comment by softsyst** [comment] 2023-02-27 21:40
Ciao Paolo,

thanks again for your help in finding a solution to this problem. The wrong database driver lets the software inevitably crash, good we could find it out thanks to your support!

If you agree, I'll close this one.

73 for now, 
Clem

**Closed as completed** 2023-02-28 15:28 UTC
